const express = require('express');
const axios = require('axios');
const Stripe = require('stripe');
const bcrypt = require('bcryptjs');
const jwt = require('jsonwebtoken');
const sqlite3 = require('sqlite3').verbose();
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
require('dotenv').config();

const app = express();
const port = Number(process.env.PORT || 4242);
const JWT_SECRET = process.env.JWT_SECRET || 'replace-this-in-production';
const stripe = process.env.STRIPE_SECRET_KEY ? Stripe(process.env.STRIPE_SECRET_KEY) : null;
const wise = axios.create({ baseURL: (process.env.WISE_API_BASE || 'https://api.wise.com').replace(/\/$/, ''), timeout: 15000, headers: { Authorization: `Bearer ${process.env.WISE_API_KEY || ''}`, 'Content-Type': 'application/json' } });
fs.mkdirSync(path.join(__dirname, 'data'), { recursive: true });
const db = new sqlite3.Database(path.join(__dirname, 'data', 'cashexc.db'));
db.exec(`CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, name TEXT NOT NULL, email TEXT UNIQUE NOT NULL, password_hash TEXT NOT NULL, receive_account TEXT, created_at TEXT DEFAULT CURRENT_TIMESTAMP); CREATE TABLE IF NOT EXISTS payments (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, amount INTEGER NOT NULL, currency TEXT NOT NULL, status TEXT NOT NULL, recipient_name TEXT, recipient_account TEXT, created_at TEXT DEFAULT CURRENT_TIMESTAMP); CREATE TABLE IF NOT EXISTS transfers (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, payment_intent_id TEXT NOT NULL UNIQUE, provider TEXT NOT NULL, provider_id TEXT, status TEXT NOT NULL, recipient_name TEXT, recipient_account TEXT, created_at TEXT DEFAULT CURRENT_TIMESTAMP);`, e => { if (e) console.error(e.message); });
const run = (sql, p=[]) => new Promise((resolve,reject)=>db.run(sql,p,function(e){e?reject(e):resolve(this)}));
const get = (sql,p=[]) => new Promise((resolve,reject)=>db.get(sql,p,(e,r)=>e?reject(e):resolve(r)));
const all = (sql,p=[]) => new Promise((resolve,reject)=>db.all(sql,p,(e,r)=>e?reject(e):resolve(r)));
const tokenFor = user => jwt.sign({ sub: user.id, email: user.email }, JWT_SECRET, { expiresIn: '2h' });
function auth(req,res,next){ const h=req.headers.authorization||''; if(!h.startsWith('Bearer ')) return res.status(401).json({error:'Login required.'}); try{req.user=jwt.verify(h.slice(7),JWT_SECRET); next();}catch(e){return res.status(401).json({error:'Invalid or expired token.'});} }
function stripeRequired(res){if(!stripe){res.status(503).json({error:'Stripe is not configured.'});return false}return true}
function amountOk(a){return Number.isFinite(Number(a))&&Number(a)>0&&Number(a)<=1000000}
app.use((req,res,next)=>{res.setHeader('Access-Control-Allow-Origin',process.env.FRONTEND_ORIGIN||'*');res.setHeader('Access-Control-Allow-Methods','GET,POST,OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type, Authorization, Stripe-Signature');if(req.method==='OPTIONS')return res.sendStatus(204);next()});
app.post('/api/payments/webhook',express.raw({type:'application/json'}),async(req,res)=>{if(!stripe||!process.env.STRIPE_WEBHOOK_SECRET)return res.status(503).json({error:'Webhook not configured.'});try{const event=stripe.webhooks.constructEvent(req.body,req.headers['stripe-signature'],process.env.STRIPE_WEBHOOK_SECRET);if(event.type.startsWith('payment_intent.')){const p=event.data.object;await run('UPDATE payments SET status=? WHERE id=?',[p.status,p.id])}res.json({received:true})}catch(e){res.status(400).send(`Webhook Error: ${e.message}`)}});
app.use(express.json({limit:'100kb'}));
app.get('/health',(_req,res)=>res.json({ok:true,wiseConfigured:Boolean(process.env.WISE_API_KEY&&process.env.WISE_PROFILE_ID)}));
app.post('/api/auth/signup',async(req,res)=>{const{name,email,password,receiveAccount=''}=req.body||{};if(!name||!email||!password||password.length<8)return res.status(400).json({error:'Name, email, and a password of at least 8 characters are required.'});try{const user={id:`user_${crypto.randomUUID()}`,name:name.trim(),email:email.trim().toLowerCase(),password_hash:await bcrypt.hash(password,12),receive_account:String(receiveAccount).trim()};await run('INSERT INTO users(id,name,email,password_hash,receive_account) VALUES(?,?,?,?,?)',[user.id,user.name,user.email,user.password_hash,user.receive_account]);delete user.password_hash;res.status(201).json({token:tokenFor(user),user:{id:user.id,name:user.name,email:user.email,receiveAccount:user.receive_account}})}catch(e){res.status(e.message.includes('UNIQUE')?409:500).json({error:e.message.includes('UNIQUE')?'Email already registered.':'Unable to create account.'})}});
app.post('/api/auth/login',async(req,res)=>{const{email,password}=req.body||{};const user=await get('SELECT * FROM users WHERE email=?',[String(email||'').toLowerCase()]);if(!user||!(await bcrypt.compare(password||'',user.password_hash)))return res.status(401).json({error:'Invalid email or password.'});res.json({token:tokenFor(user),user:{id:user.id,name:user.name,email:user.email,receiveAccount:user.receive_account}})});
app.get('/api/auth/me',auth,async(req,res)=>{const u=await get('SELECT id,name,email,receive_account FROM users WHERE id=?',[req.user.sub]);if(!u)return res.status(401).json({error:'Account not found.'});res.json({user:{...u,receiveAccount:u.receive_account}})});
app.post('/api/payments/create-intent',auth,async(req,res)=>{if(!stripeRequired(res))return;const{amount,currency='USD',recipientName='',recipientAccount=''}=req.body||{};if(!amountOk(amount))return res.status(400).json({error:'Invalid amount.'});try{const p=await stripe.paymentIntents.create({amount:Math.round(Number(amount)*100),currency:String(currency).toLowerCase(),payment_method_types:['card'],confirmation_method:'automatic',metadata:{user_id:req.user.sub,recipient_name:String(recipientName).slice(0,200),recipient_account:String(recipientAccount).slice(0,200)}});await run('INSERT INTO payments(id,user_id,amount,currency,status,recipient_name,recipient_account) VALUES(?,?,?,?,?,?,?)',[p.id,req.user.sub,p.amount,p.currency,p.status,recipientName,recipientAccount]);res.json({clientSecret:p.client_secret,paymentIntentId:p.id})}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/transfers/execute',auth,async(req,res)=>{if(!stripeRequired(res))return;if(!process.env.WISE_API_KEY||!process.env.WISE_PROFILE_ID)return res.status(503).json({error:'Wise credentials are not configured.'});const{paymentIntentId,recipientName,iban,recipientAccount,bankCountry='US',targetCurrency='EUR',reference='Cashex transfer'}=req.body||{};const account=iban||recipientAccount;if(!paymentIntentId||!recipientName||!account)return res.status(400).json({error:'Payment, recipient name, and IBAN/account are required.'});try{const p=await stripe.paymentIntents.retrieve(paymentIntentId);if(p.metadata.user_id!==req.user.sub)return res.status(403).json({error:'Payment does not belong to this account.'});if(p.status!=='succeeded')return res.status(409).json({error:'Payment must be succeeded before payout.'});const old=await get('SELECT * FROM transfers WHERE payment_intent_id=?',[paymentIntentId]);if(old)return res.json({ok:true,transfer:old,duplicate:true});const currency=String(targetCurrency).toUpperCase();const q=await wise.post('/v2/quotes',{profile:Number(process.env.WISE_PROFILE_ID),sourceCurrency:String(p.currency).toUpperCase(),targetCurrency:currency,sourceAmount:p.amount/100,payOut:'BANK_TRANSFER'});const r=await wise.post('/v1/accounts',{profile:Number(process.env.WISE_PROFILE_ID),accountHolderName:recipientName,currency,type:'iban',details:{iban:String(account).replace(/\s/g,'').toUpperCase()}});const t=await wise.post('/v1/transfers',{targetAccount:r.data.id,quoteUuid:q.data.id,customerTransactionId:`cashexc_${crypto.randomUUID()}`,details:{reference:String(reference).slice(0,140)}});const f=await wise.post(`/v3/profiles/${process.env.WISE_PROFILE_ID}/transfers/${t.data.id}/payments`,{type:'BALANCE'});const transfer={id:`transfer_${crypto.randomUUID()}`,userId:req.user.sub,paymentIntentId,provider:'wise',providerId:String(t.data.id),status:f.data.status||t.data.status||'processing',recipientName,recipientAccount:account};await run('INSERT INTO transfers(id,user_id,payment_intent_id,provider,provider_id,status,recipient_name,recipient_account) VALUES(?,?,?,?,?,?,?,?)',[transfer.id,transfer.userId,transfer.paymentIntentId,transfer.provider,transfer.providerId,transfer.status,recipientName,account]);res.status(202).json({ok:true,transfer})}catch(e){res.status(502).json({error:e.response?.data?.message||e.message})}});
app.get('/api/transfers',auth,async(req,res)=>res.json({transfers:await all('SELECT * FROM transfers WHERE user_id=? ORDER BY created_at DESC',[req.user.sub])}));
app.listen(port,()=>console.log(`Cashex server listening on ${port}`));
